name: release
on:
  push:
    branches: [main]
jobs:
  release:
    uses: opencapital-dev/opencapital/.github/workflows/plugin-release.yml@main
    permissions:
      contents: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      id: core-app
      owner: opencapital-dev
      platforms: darwin-amd64,darwin-arm64,windows-amd64
